### ISSUE TITLE
Error with ResNet18 and Resnet34 (BasicBlock in Resnet)

### ISSUE THREAD

**Issue by susmitjha** [wjNam/Relative_Attributing_Propagation#1]
It appears there is a bug when attempting to use the attribution method for ResNet18/Resnet34 model. Resnet50 works fine. Perhaps, there is a bug in BasicBlock class. Could you please take a look? The error trace is below.

```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    RAP = model.RAP_relprop(R=T)
  File "Relative_Attributing_Propagation/modules/resnet.py", line 335, in RAP_relprop
    R = self.layer4.RAP_relprop(R)
  File "Relative_Attributing_Propagation/modules/layers.py", line 207, in RAP_relprop
    Rp = m.RAP_relprop(Rp)
  File "Relative_Attributing_Propagation/modules/resnet.py", line 113, in RAP_relprop
    return self.clone.RAP_relprop([x1, x2])
  File "Relative_Attributing_Propagation/modules/layers.py", line 154, in RAP_relprop
    Rp_tmp = backward(tmp_R_p[i])
  File "Relative_Attributing_Propagation/modules/layers.py", line 139, in backward
    for z, rp, rn in zip(Z, R_p):
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by wjNam** [comment]
Hi, I can't see your error in my environment.
I think it is because of the clone function.
Please try the code after comment the clone function in resnet.py

**Comment by susmitjha** [comment]
Thanks. That works in the sense of giving an output without crashing. I got rid of clone in BasicBlock class. I am not sure if my fix has introduced some other bug. Is it possible for you to push a fix with clone removed?

**Comment by wjNam** [comment]
clone function does not affect on the relevance propagation, so the result would be the same.
I will update my code soon.
Thank you.
